-- 코드를 입력하세요
SELECT FOOD_TYPE,	REST_ID,	REST_NAME,	MAX(FAVORITES) as FAVORITES
FROM REST_INFO
WHERE FAVORITES in
    (SELECT MAX(FAVORITES) as FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE)
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE desc


