-- 코드를 입력하세요
SELECT USER_ID,	NICKNAME, CONCAT(CITY, " ", STREET_ADDRESS1, " ", STREET_ADDRESS2) as 전체주소, 
CONCAT(SUBSTRING(TLNO, 1, 3), '-',
       SUBSTRING(TLNO, 4, 4), '-',
       SUBSTRING(TLNO, 8, 4)
      ) as 전화번호
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_USER U
ON B.WRITER_ID = U.USER_ID
GROUP BY U.USER_ID, U.NICKNAME, CITY, STREET_ADDRESS1, STREET_ADDRESS2, TLNO
HAVING count(*) >= 3
ORDER BY USER_ID desc