-- 대여중인 애들을 다 꺼내고 나머지 애들은 대여 가능으로 
--  


((SELECT CAR_ID, '대여 가능' as AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID NOT IN (SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATE('2022-10-16') BETWEEN START_DATE and END_DATE))

UNION 

(SELECT CAR_ID, '대여중' as AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATE('2022-10-16') BETWEEN START_DATE and END_DATE)))

ORDER BY CAR_ID desc





