-- 코드를 입력하세요
# SELECT P.PRODUCT_ID,	PRODUCT_NAME,	SUM(P.PRICE * O.AMOUNT) as TOTAL_SALES
# FROM FOOD_PRODUCT P
# JOIN FOOD_ORDER O
# ON P.PRODUCT_ID = O.PRODUCT_ID
# WHERE YEAR(O.PRODUCE_DATE) = 2022 and MONTH(O.PRODUCE_DATE) = 5
# GROUP BY PRODUCT_ID


SELECT P.PRODUCT_ID, PRODUCT_NAME, SUM(P.PRICE * O.AMOUNT) as TOTAL_SALES
FROM FOOD_PRODUCT P
JOIN FOOD_ORDER O
ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE YEAR(O.PRODUCE_DATE) = 2022 and MONTH(O.PRODUCE_DATE) = 5
GROUP BY PRODUCT_ID, PRODUCT_NAME
ORDER BY TOTAL_SALES desc , P.PRODUCT_ID 