-- 코드를 입력하세요
SELECT P.PRODUCT_ID, PRODUCT_NAME, SUM(PRICE * AMOUNT) as TOTAL_SALES
FROM FOOD_ORDER O
JOIN FOOD_PRODUCT P
ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE P.PRODUCT_ID IN (SELECT PRODUCT_ID
                    FROM FOOD_ORDER 
                    WHERE YEAR(PRODUCE_DATE) = 2022 and MONTH(PRODUCE_DATE) = 5)
and YEAR(PRODUCE_DATE) = 2022 and MONTH(PRODUCE_DATE) = 5
                    
GROUP BY PRODUCT_ID, PRODUCT_NAME
ORDER BY TOTAL_SALES desc , PRODUCT_ID