-- 코드를 입력하세요
SELECT APNT_NO,	PT_NAME,	A.PT_NO,	A.MCDP_CD,	DR_NAME, APNT_YMD
FROM APPOINTMENT A
JOIN PATIENT P
ON A.PT_NO = P.PT_NO
JOIN DOCTOR D
ON A.MDDR_ID = D.DR_ID
WHERE D.MCDP_CD = 'CS' and YEAR(APNT_YMD) = 2022 and MONTH(APNT_YMD) = 4 and DAY(APNT_YMD) = 13 and APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD