
SELECT MEMBER_NAME,	REVIEW_TEXT,	REVIEW_DATE
FROM REST_REVIEW R
JOIN MEMBER_PROFILE P
ON R.MEMBER_ID = P.MEMBER_ID
WHERE P.MEMBER_ID = 
(
SELECT MEMBER_ID
FROM REST_REVIEW
GROUP BY MEMBER_ID  
ORDER BY count(*) desc 
LIMIT 1
)


ORDER BY REVIEW_DATE, REVIEW_TEXT