with max_reviewer as (SELECT MEMBER_ID
FROM REST_REVIEW
GROUP BY MEMBER_ID
ORDER BY COUNT(*) desc
LIMIT 1)


SELECT MEMBER_NAME,	REVIEW_TEXT,	REVIEW_DATE
FROM MEMBER_PROFILE P
JOIN REST_REVIEW R
ON P.MEMBER_ID = R.MEMBER_ID
WHERE R.MEMBER_ID = (select * from max_reviewer )
ORDER BY REVIEW_DATE , REVIEW_TEXT

