with five_up as (SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE BETWEEN DATE('2022-08-01') and DATE('2022-10-31')
GROUP BY CAR_ID
HAVING COUNT(*) >= 5)

SELECT MONTH(START_DATE) as MONTH, CAR_ID,	count(*) as RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE BETWEEN DATE('2022-08-01') and DATE('2022-10-31')
and CAR_ID in (SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE BETWEEN DATE('2022-08-01') and DATE('2022-10-31')
GROUP BY CAR_ID
HAVING COUNT(*) >= 5)
GROUP BY CAR_ID, MONTH
ORDER BY MONTH, CAR_ID desc
