-- 코드를 입력하세요
SELECT DISTINCT I.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR I
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON I.CAR_ID = H.CAR_ID
WHERE MONTH(START_DATE) = 10 and CAR_TYPE = '세단'
ORDER BY CAR_ID desc
