-- 코드를 입력하세요
SELECT TITLE,	B.BOARD_ID,	REPLY_ID,	R.WRITER_ID,	R.CONTENTS,	DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE 
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_REPLY R ON B.BOARD_ID = R.BOARD_ID
WHERE YEAR(B.CREATED_DATE) = 2022 and MONTH(B.CREATED_DATE) = 10
ORDER BY R.CREATED_DATE asc, TITLE asc