-- 코드를 입력하세요
# SELECT CATEGORY, MAX(PRICE) as MAX_PRICE,	PRODUCT_NAME
# FROM FOOD_PRODUCT
# WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
# GROUP BY CATEGORY
# ORDER BY MAX_PRICE desc 


SELECT CATEGORY, PRICE,	PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE PRICE in (SELECT MAX(PRICE)
       FROM FOOD_PRODUCT
       GROUP BY CATEGORY
) and CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY PRICE desc 

